### ISSUE TITLE
Invalid server mode "staging"

### ISSUE THREAD

**Issue by Xiphe** [remix-run/starter-architect#1]
When I follow the readme and deploy the app, I receive an `{"message":"Internal Server Error"}` in the frontend.

In cloudwatch it says: 
```
2021-01-31T00:41:56.441Z	undefined	ERROR	Error: Invalid server mode "staging" 
at Object.readConfig (/var/task/node_modules/@remix-run/core/config.js:33:11) 
at createPlatformRequestHandler (/var/task/node_modules/@remix-run/core/adapter.js:22:37)
at Object.<anonymous> (/var/task/index.js:2:19)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at _tryRequire (/var/runtime/UserFunction.js:75:12)
```

**Comment by Xiphe** [comment]
works with `arc deploy production` I can work with that. In the future I'd like to also use other stages though

**Comment by mjackson** [comment]
Thanks for the issue, but we are archiving this repo. We have a new `npm init remix` command that we are recommending people use to get started instead of the starter repos, so I'm closing all the issues here.

If this is still bugging you, would you mind opening an issue about it in https://github.com/remix-run/discuss ? Thanks!
